# filters out notebook metadata like kernel
notebook_metadata_filter = "-all"

# filters out cell tags metadata
cell_metadata_filter = "-all"

# Always pair ipynb notebooks to py:percent files
# formats = ["ipynb", "py:percent"]
# Pair notebooks in subfolders of 'notebooks' to scripts in subfolders of 'scripts'
[formats]
"notebooks/" = "ipynb"
"notebooks_src/" = "py:percent"
